name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 13 * * 1-5"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kierun
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Europe/London
          config_twemoji: yes

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Activities plugin
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Language plugin
          # Indepth analysis: https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin_languages_details: bytes-size, line, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_analysis_timeout: 15

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: yes

          # People plugin
          plugin_people: yes
          plugin_people_limit: 150
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # plugin_reactions: https://github.com/lowlighter/metrics/blob/master/source/plugins/reactions/README.md
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
